
# ICAT User roles
ICAT_USER_ROLE_PRINCIPAL_INVESTIGATOR = 'Principal investigator'
ICAT_USER_ROLE_PROPOSER = 'Proposer'
ICAT_USER_ROLE_LOCAL_CONTACT = 'Local Contact'
ICAT_USER_ROLE_COLLABORATOR = 'Collaborator'

ICAT_EMBARGO_YEARS_AMOUNT = 3
