multiprocessStartMethod: "spawn"
logging:
  logLevel: "DEBUG"
  #printFormat:
  console:
    enabled: true
  file:
    enabled: true
    path: "/opt/project/asd.log"
    rotate: true
    maxMBytes: 100
    backupCount: 5
  elastic:
    enabled: false
    serverUrl: "https://user:password@elastic-host:9200"
    serviceName: "icat-pacer"
    serviceEnvironment: "local"
    indexName: "pacer-logs"
exchanges:
  - name: "dashboard-logging-exchange"
    type: "direct"
  - name: "dead-letters-exchange"
    type: "direct"
  - name: "uos-sync-exchange"
    type: "direct"
  - name: "investigation-ops-exchange"
    type: "direct"
  - name: "dataset-ingest-exchange"
    type: "direct"
  - name: "dataset-internal-ingest-exchange"
    type: "direct"
queues:
  - name: "dashboard-logging"
    exchange: "dashboard-logging-exchange"
    routingKey: "message.logging"
  - name: "dead-letters"
    exchange: "dead-letters-exchange"
    routingKey: "dead.letters"
  - name: "uos-sync-users"
    exchange: "uos-sync-exchange"
    routingKey: "uos_user.sync"
  - name: "uos-sync-proposals"
    exchange: "uos-sync-exchange"
    routingKey: "uos_proposal.sync"
  - name: "icat-investigation-ops"
    exchange: "investigation-ops-exchange"
    routingKey: "investigation.ops"
  - name: "icat-dataset-ingest"
    exchange: "dataset-ingest-exchange"
    routingKey: "dataset.ingest"
    priorityEnabled: true
    maxPriorityLevel: 10
  - name: "icat-internal-dataset-ingest"
    exchange: "dataset-internal-ingest-exchange"
    routingKey: "dataset.internal_ingest"
    priorityEnabled: true
    maxPriorityLevel: 10
  - name: "icat-internal-statistics"
    exchange: "dataset-internal-ingest-exchange"
    routingKey: "statistics.internal_ingest"
    priorityEnabled: true
    maxPriorityLevel: 10
  - name: "icat-internal-dataset-links"
    exchange: "dataset-internal-ingest-exchange"
    routingKey: "dataset.internal_links"
    priorityEnabled: true
    maxPriorityLevel: 10
consumers:
  - className: "DeadLettersConsumer"
    module: "consumers.dead_letters"
    enabled: true
    queues:
      - "dead-letters"
    workers: 1
    integrations: [ ]
  - className: "UsersConsumer"
    module: "consumers.users"
    enabled: true
    queues:
      - "uos-sync-users"
    workers: 1
    integrations:
      - "dashboard"
      - "messageForwarding"
      - "icat"
      - "visa"
  - className: "InvestigationConsumer"
    module: "consumers.investigations"
    enabled: true
    queues:
      - "uos-sync-proposals"
    workers: 1
    integrations:
      - "dashboard"
      - "messageForwarding"
      - "icat"
      - "visa"
  - className: "InvestigationOperationsConsumer"
    module: "consumers.investigation_ops"
    enabled: true
    queues:
      - "icat-investigation-ops"
    workers: 1
    integrations:
      - "dashboard"
      - "icat"
      - "visa"
      - "datacite"
      - "panosc"
  - className: "DatasetsConsumer"
    module: "consumers.datasets"
    enabled: true
    queues:
      - "icat-dataset-ingest"
    workers: 1
    integrations:
      - "dashboard"
      - "icat"
  - className: "InternalDatasetsConsumer"
    module: "consumers.datasets"
    enabled: true
    queues:
      - "icat-internal-dataset-ingest"
    workers: 1
    integrations:
      - "dashboard"
      - "icat"
      - "icatPlus"
  - className: "InternalStatisticsConsumer"
    module: "consumers.internal_statistics"
    enabled: true
    queues:
      - "icat-internal-statistics"
    workers: 1
    integrations:
      - "dashboard"
      - "icat"
  - className: "InternalDatasetsLinksConsumer"
    module: "consumers.internal_dataset_links"
    enabled: true
    queues:
      - "icat-internal-dataset-links"
    workers: 1
    integrations:
      - "dashboard"
      - "icat"
brokers:
  main:
    protocol: "amqp"
    host: "<<REDACTED>>"
    #port:
    username: "<<REDACTED>>"
    password: "<<REDACTED>>"
    vHost: "<<REDACTED>>"
  #recipients:
  #  - name: "pacer-prod"
  #    protocol: "amqp"
  #    host: "<<REDACTED>>"
  #    #port:
  #    username: "pacer-prod"
  #    password: "<<REDACTED>>"
  #    vHost: "icat-prod"
  #    forwardingRules:
  #      - fromExchange: "uos-sync-exchange"
  #        toBroker: "pacer-prod"
ingestionSettings:
  messageProcessingRetries: 15
  dataset:
    acceptXMLPayloads: true
    mandatoryPathsExistence: false
    mandatorySampleType: false
    checkAllowedLocationPaths: true
    allowedRootLocationPaths:
      - "/beamlines"
    internalDatasetExchangeName: "dataset-internal-ingest-exchange"
    internalDatasetRoutingKey: "dataset.internal_ingest"
    internalStatisticsRoutingKey: "statistics.internal_ingest"
    internalDatasetLinksRoutingKey: "dataset.internal_links"
    automaticDatasetLocationIndex: true
    maxDatafilesPerDataset: 30000
    galleryFolderName: "gallery"
    #xmlNamespacesTransform:
    #  - schema: "http://www.esrf.fr/icat"
    #    to: null
    #galleryAcceptedUploadTypes:
    #  - ".lel"
  investigation:
    defaultEmbargoYears: 3
    defaultFacilityName: "ALBA"
  parameters:
    storeParametersValuesAlsoAsString: true
integrations:
  visa:
    enabled: true
    database:
      host: "<<REDACTED>>"
      port: "<<REDACTED>>"
      database: "<<REDACTED>>"
      user: "<<REDACTED>>"
      password: "<<REDACTED>>"
  icat:
    enabled: true
    server:
      url: "https://<<REDACTED>>/ICATService/ICAT?wsdl"
      authPlugin: "db"
      username: "<<REDACTED>>"
      password: "<<REDACTED>>"
  dashboard:
    enabled: true
    exchangeName: "dashboard-logging-exchange"
    routingKey: "message.logging"
    celeryTask: "dashboard.tasks.log_pacer_message"
  datacite:
    enabled: true
    dataCatalogueDoiBaseUrl: "https://doi.cells.es/"
    publisher: "ALBA Synchrotron"
    prefix: "DOI PREFIX"
    sessionSuffix: "TEST-ALBA-"
    username: "<<REDACTED>>"
    password: "<<REDACTED>>"
    apiUrl: "https://api.test.datacite.org"
    language: "en"
    rightsName: "Creative Commons Attribºution 4.0 International"
    rightsSchemeUri: "https://spdx.org/licenses/"
    rightsUri: "https://creativecommons.org/licenses/by/4.0/"
    rightsIdentifierScheme: "SPDX"
    rightsIdentifier: "CC-BY-4.0"
    funderName: "ALBA Synchrotron"
    funderIdentifier: "https://ror.org/02j9n6e35"
    funderIdentifierType: "ROR"
  panosc:
    enabled: true
    apiUrl: "https://scoring-svc"
    username: "<<REDACTED>>"
    password: "<<REDACTED>>"
    searchApiUrl: "https://data.cells.es/iws/datagateway/search-api"
  icatPlus:
    enabled: true
    server:
      url: "https://icattest.cells.es/iws/icat_plus/"
      apiKey: "<<REDACTED>>"